In [8]:
import numpy as np #넘파이는 행렬

In [117]:
arr_1 = np.array(range(10)) #[1,2,3,4,5,6,7,8,9]
print(arr_1)
print(arr_1.shape)  #1,2,3..은 모두 행
print(f'arr_1의 차원: {arr_1.ndim}, \n\n') 

arr_2 = np.array([[1,2,3],[1,2,3]])
print(arr_2)
print(arr_2.shape)
print(f'arr_2의 차원: {arr_2.ndim}, \n\n')

arr_3 = np.array([[[1,2,3],[1,2,3]],[[1,2,3],[1,2,3]]])
print(arr_3)
print(arr_3.shape)
print(f'arr_3의 차원: {arr_3.ndim}, \n')

[0 1 2 3 4 5 6 7 8 9]
(10,)
arr_1의 차원: 1, 


[[1 2 3]
 [1 2 3]]
(2, 3)
arr_2의 차원: 2, 


[[[1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]]]
(2, 2, 3)
arr_3의 차원: 3, 



In [118]:
arr1 = np.arange(start =2, stop = 20).reshape(-1,3) # -1을 넣으면 나머지 차원에 맞도록 알아서
print(arr1)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]
 [11 12 13]
 [14 15 16]
 [17 18 19]]


In [292]:
print(arr1[2], '\n')
print(arr1[1:3],'\n') #행 슬라이싱
print(arr1[:,1:3]) #열 슬라이싱 하려면 @@@@  ',' 로 구분 후 행에 ':' 를 꼭 넣어줘야 함

[ 8  9 10] 

[[ 5  6  7]
 [ 8  9 10]] 

[[ 3  4]
 [ 6  7]
 [ 9 10]
 [12 13]
 [15 16]
 [18 19]]


In [299]:
#위에처럼도 같음
arr1[3][2]
arr1[3,2]

13

In [53]:
#불린 인덱싱 - 조건 검색
arr1d = arr1[arr1>10]
print(arr1d)

[11 12 13 14 15 16 17 18 19]


In [85]:
# 정렬
arr1_desc = np.sort(arr1)[::-1]
print(arr1_desc)

arr1_asc = np.sort(arr1_desc)  #열 정렬이라 그대로 == axis=1
print(arr1_asc)

arr1_sort = np.sort(arr1_desc, axis=0) #행 정렬
print(arr1_sort)

[[17 18 19]
 [14 15 16]
 [11 12 13]
 [ 8  9 10]
 [ 5  6  7]
 [ 2  3  4]]
[[17 18 19]
 [14 15 16]
 [11 12 13]
 [ 8  9 10]
 [ 5  6  7]
 [ 2  3  4]]
[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]
 [11 12 13]
 [14 15 16]
 [17 18 19]]


In [9]:
import pandas as pd

In [76]:
Series  : 열이 1개
Data frame : 열이 여러개
공통점 : 고유값 index로 식별

SyntaxError: invalid syntax (3835445590.py, line 1)

In [10]:
titanic_df = pd.read_csv('train.csv')
print(titanic_df.head(3))
titanic_df.head(3)  #print가 없이 사용하면 이뿌게 나옴

   PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  


PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S

In [9]:
titanic_df.info() #Age칼럼의 non-null이 714개이므로 891-714개 만큼은 null이다

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [11]:
titanic_df.describe() #데이터 분포도

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [19]:
v_count = titanic_df['Pclass'].value_counts()   # 특정 컬럼 데이터 종류별 개수
print(v_count)

3    491
1    216
2    184
Name: Pclass, dtype: int64


In [25]:
print(titanic_df['Pclass'].head(10))
print(type(titanic_df))
print(type(titanic_df['Pclass'])) #인덱스 한줄과 컬럼 한 줄로만 구성

0    3
1    1
2    3
3    1
4    3
5    3
6    1
7    3
8    3
9    2
Name: Pclass, dtype: int64
<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.series.Series'>


In [68]:
print(titanic_df[3:5]) # numpy와 같이 행 슬라이싱은 :을 사용
print('\n-----------------------\n')
#titanic_df[3:5,'Pclass'] 불가능. 행과 열 한꺼번에 슬라이싱 하려면 loc[]
print(titanic_df.loc[4:,'Pclass':'Parch'].head())

   PassengerId  Survived  Pclass  \
3            4         1       1   
4            5         0       3   

                                           Name     Sex   Age  SibSp  Parch  \
3  Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1      0   
4                      Allen, Mr. William Henry    male  35.0      0      0   

   Ticket   Fare Cabin Embarked  
3  113803  53.10  C123        S  
4  373450   8.05   NaN        S  

-----------------------

   Pclass                                               Name     Sex   Age  \
4       3                           Allen, Mr. William Henry    male  35.0   
5       3                                   Moran, Mr. James    male   NaN   
6       1                            McCarthy, Mr. Timothy J    male  54.0   
7       3                     Palsson, Master. Gosta Leonard    male   2.0   
8       3  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0   

   SibSp  Parch  
4      0      0  
5      0      0  
6 

In [77]:
titanic_df['Number'] = np.arange(start=1 , stop=892) #새로운 열 생성 및 np사용해 1부터 끝번까지 숫자부여
print(titanic_df[0:5])

   PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  Number  
0      0         A/5 21171   7.2500   NaN        S       1  
1      0          PC 17599  71.2833   C85        C       2  
2      0  STON/O2. 3101282   7.9250   NaN        S       3  
3      0            113803  53.1000  C123        S       4  
4      0       

In [87]:
titanic_drop_df = titanic_df.drop('Number',axis=1)   #필요없는 컬럼 삭제. 원본은 삭제 안 됨
print(titanic_drop_df.head())  #axis=0이면 행을 삭제 (ex:이상치 데이터), 1이면 열 삭제 

   PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S  


In [93]:
print(titanic_df.index)
print(titanic_df.index.values)

RangeIndex(start=0, stop=891, step=1)
[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 

In [96]:
new_ti = titanic_df['Fare']+3    #모든 데이터에 3더해주기
print(new_ti)

0      10.2500
1      74.2833
2      10.9250
3      56.1000
4      11.0500
        ...   
886    16.0000
887    33.0000
888    26.4500
889    33.0000
890    10.7500
Name: Fare, Length: 891, dtype: float64


In [106]:
#인덱스 새로 형성. 기존의 인덱스는 index라는 열로 이름 변경됨
titanic_reset_df = titanic_df.reset_index(inplace=False) #inplace=False라 원본은 바뀌지 않음
print(titanic_reset_df)

     index  PassengerId  Survived  Pclass  \
0        0            1         0       3   
1        1            2         1       1   
2        2            3         1       3   
3        3            4         1       1   
4        4            5         0       3   
..     ...          ...       ...     ...   
886    886          887         0       2   
887    887          888         1       1   
888    888          889         0       3   
889    889          890         1       1   
890    890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  

In [120]:
# wow
val_count = titanic_df['Pclass'].value_counts()
print(val_count)   #Pclass의 클래스1,2,3 각각의 개수를 요약
val_index_count = val_count.reset_index()
print(val_index_count) #새 인덱스를 추가해 기존의 인덱스 3,1,2는 보통의 컬럼으로 자리하고 컬럼 라벨도 나타남
print(titanic_df.columns[2])

3    491
1    216
2    184
Name: Pclass, dtype: int64
   index  Pclass
0      3     491
1      1     216
2      2     184
Pclass


In [167]:
#넘파이는 arr[1], arr[0,1]로 열,행 가능 VS 데이터프레임은 df[0:2] 처럼 연속된 슬라이싱 형태로 '행'슬라이싱. 열은 칼럼명으로만 가능
titanic_df[0:2]
#titanic_df[1] # X


PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   

   Parch     Ticket     Fare Cabin Embarked  
0      0  A/5 21171   7.2500   NaN        S  
1      0   PC 17599  71.2833   C85        C

In [148]:
#넘파이와 마찬가지로 불린 인덱싱 가능
titanic_df[titanic_df['Pclass']==3].head(4)

PassengerId  Survived  Pclass                      Name     Sex   Age  \
0            1         0       3   Braund, Mr. Owen Harris    male  22.0   
2            3         1       3    Heikkinen, Miss. Laina  female  26.0   
4            5         0       3  Allen, Mr. William Henry    male  35.0   
5            6         0       3          Moran, Mr. James    male   NaN   

   SibSp  Parch            Ticket    Fare Cabin Embarked  Number  
0      1      0         A/5 21171  7.2500   NaN        S       1  
2      0      0  STON/O2. 3101282  7.9250   NaN        S       3  
4      0      0            373450  8.0500   NaN        S       5  
5      0      0            330877  8.4583   NaN        Q       6

In [170]:
#iloc[] 을 사용하면 데이터프레임도 넘파이와같이 열의 위치만으로 슬라이싱 가능 
titanic_df.iloc[:,1:4] #주의: iloc은 위치기반으로 숫자만 사용.
#titanic_df.iloc[1].head()
#titanic_df.iloc[1,2] #콕 찝어서는 :없이 가능

Survived  Pclass                                               Name
0           0       3                            Braund, Mr. Owen Harris
1           1       1  Cumings, Mrs. John Bradley (Florence Briggs Th...
2           1       3                             Heikkinen, Miss. Laina
3           1       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)
4           0       3                           Allen, Mr. William Henry
..        ...     ...                                                ...
886         0       2                              Montvila, Rev. Juozas
887         1       1                       Graham, Miss. Margaret Edith
888         0       3           Johnston, Miss. Catherine Helen "Carrie"
889         1       1                              Behr, Mr. Karl Howell
890         0       3                                Dooley, Mr. Patrick

[891 rows x 3 columns]

In [175]:
titanic_df.iloc[:,::-1] #열 거꾸로
#titanic_df.iloc[:,-1] 맨 뒤의 열

Embarked Cabin     Fare            Ticket  Parch  SibSp   Age     Sex  \
0          S   NaN   7.2500         A/5 21171      0      1  22.0    male   
1          C   C85  71.2833          PC 17599      0      1  38.0  female   
2          S   NaN   7.9250  STON/O2. 3101282      0      0  26.0  female   
3          S  C123  53.1000            113803      0      1  35.0  female   
4          S   NaN   8.0500            373450      0      0  35.0    male   
..       ...   ...      ...               ...    ...    ...   ...     ...   
886        S   NaN  13.0000            211536      0      0  27.0    male   
887        S   B42  30.0000            112053      0      0  19.0  female   
888        S   NaN  23.4500        W./C. 6607      2      1   NaN  female   
889        C  C148  30.0000            111369      0      0  26.0    male   
890        Q   NaN   7.7500            370376      0      0  32.0    male   

                                                  Name  Pclass  Survived  \
0                              Braund, Mr. Owen Harris       3         0   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...       1         1   
2                               Heikkinen, Miss. Laina       3         1   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)       1         1   
4                             Allen, Mr. William Henry       3         0   
..                                                 ...     ...       ...   
886                              Montvila, Rev. Juozas       2         0   
887                       Graham, Miss. Margaret Edith       1         1   
888           Johnston, Miss. Catherine Helen "Carrie"       3         0   
889                              Behr, Mr. Karl Howell       1         1   
890                                Dooley, Mr. Patrick       3         0   

     PassengerId  
0              1  
1              2  
2              3  
3              4  
4              5  
..           ...  
886          887  
887          888  
888          889  
889          890  
890          891  

[891 rows x 12 columns]

In [190]:
##데이터프레임의 형식 : 딕셔너리. --> 엑셀과 같은 데이터를 불러오지 않고도 직접 DataFrame으로 변경가능##
data = {'Name':['jiho','sangjun','kyunghoon'], 'Year':[2000,2001,2002], 'Gender':['Male','Female','Male']}
data_df = pd.DataFrame(data, index =['ONE','TWO','TRHEE'])
data_df

Name  Year  Gender
ONE         jiho  2000    Male
TWO      sangjun  2001  Female
TRHEE  kyunghoon  2002    Male

In [192]:
#lioc이 위치기반 VS  loc은 명칭기반. 숫자 X
data_df.loc['ONE', 'Name']

'jiho'

In [282]:
#정렬
name_df = titanic_df.sort_values(by=['Name'], ascending=True) #칼럼 여러개 가능
name_df[0:3]

PassengerId  Survived  Pclass                              Name     Sex  \
845          846         0       3               Abbing, Mr. Anthony    male   
746          747         0       3       Abbott, Mr. Rossmore Edward    male   
279          280         1       3  Abbott, Mrs. Stanton (Rosa Hunt)  female   

      Age  SibSp  Parch     Ticket   Fare Cabin Embarked  Name_len    C/A  \
845  42.0      0      0  C.A. 5547   7.55  C000        S       891  adult   
746  16.0      1      1  C.A. 2673  20.25  C000        S       891  child   
279  35.0      1      1  C.A. 2673  20.25  C000        S       891  adult   

     C/A/E  
845  adult  
746  child  
279  adult

In [288]:
#데이터프레임을 numpy array로 만들어줌
titanic_df.values

array([[1, 0, 3, ..., 891, 'adult', 'adult'],
       [2, 1, 1, ..., 891, 'adult', 'adult'],
       [3, 1, 3, ..., 891, 'adult', 'adult'],
       ...,
       [889, 0, 3, ..., 891, 'adult', 'adult'],
       [890, 1, 1, ..., 891, 'adult', 'adult'],
       [891, 0, 3, ..., 891, 'adult', 'adult']], dtype=object)

In [290]:
#numpy array의 1개의 열 형태로 --> 회귀분석에 필요
titanic_df['PassengerId'].head(10).values.reshape(-1,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]], dtype=int64)

In [207]:
#Aggregation 집계함수. 각 컬럼별 집계. min(),max(),sum()...
titanic_df['Age'].mean()
#titanic_df[['Age','Fare']].mean() #여러개 컬럼


29.69911764705882

In [210]:
titanic_df.count() #모든 컬럼.

PassengerId    891
Survived       891
Pclass         891
Name           891
Sex            891
Age            714
SibSp          891
Parch          891
Ticket         891
Fare           891
Cabin          204
Embarked       889
dtype: int64

In [221]:
#groupby : 그룹으로 묶으면 이를 집계함수로 묶어줘야함. 그룹마다 하나의 행으로 표현하기 위해
titanic_df.groupby('Pclass').count()
#titanic_df.groupby('Pclass')[['PassengerId','Survived']].count() #컬럼 두 개만 추출

PassengerId  Survived  Name  Sex  Age  SibSp  Parch  Ticket  Fare  \
Pclass                                                                      
1               216       216   216  216  186    216    216     216   216   
2               184       184   184  184  173    184    184     184   184   
3               491       491   491  491  355    491    491     491   491   

        Cabin  Embarked  
Pclass                   
1         176       214  
2          16       184  
3          12       491

In [222]:
#null 널 값 처리
titanic_df.isna().head(3)

PassengerId  Survived  Pclass   Name    Sex    Age  SibSp  Parch  Ticket  \
0        False     False   False  False  False  False  False  False   False   
1        False     False   False  False  False  False  False  False   False   
2        False     False   False  False  False  False  False  False   False   

    Fare  Cabin  Embarked  
0  False   True     False  
1  False  False     False  
2  False   True     False

In [228]:
#널값의 개수 구하기 
titanic_df.isna().sum() 
#titanic_df.isna().count() #isna()로 널값에 True를 넣음으로 count를 하면 모든 데이터가 읽힘. 그러므로 sum().

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [237]:
#결손 데이터 대체 / #실제 데이터를 변경하려면 fillna('C000', inplace=True)
titanic_df['Cabin'] = titanic_df['Cabin'].fillna('C000')
titanic_df.head(4)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500  C000        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250  C000        S  
3      0            113803  53.1000  C123        S

In [242]:
#나이의 결측치에 나이의 평균(결측치 제외한) 
titanic_df['Age'] = titanic_df['Age'].fillna(titanic_df['Age'].mean())

In [248]:
#판다스식 lambda. ex) 'Name'의 글자길이로 새로운 컬럼 형성. ap을 사용하지 않음
titanic_df["Name_len"] = titanic_df['Name'].apply(lambda x: len(x))
titanic_df[['Name', 'Name_len']].head()

Name  Name_len
0                            Braund, Mr. Owen Harris        23
1  Cumings, Mrs. John Bradley (Florence Briggs Th...        51
2                             Heikkinen, Miss. Laina        22
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)        44
4                           Allen, Mr. William Henry        24

In [249]:
# X -> 각 행별 len이 아닌 {Name: [, , , , ]}의 값들 전체를 취급
# lambda를 사용해야 행별로 각각 계산해야 됨
titanic_df['Name_len'] = len(titanic_df['Name'])
titanic_df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  Name_len  
0      0         A/5 21171   7.2500  C000        S       891  
1      0          PC 17599  71.2833   C85        C       891  
2      0  STON/O2. 3101282   7.9250  C000        S       891  
3      0            113803  53.1000  C123        S       891  
4      0            373450   8.0500  C000        S       891

In [273]:
#if를 사용
titanic_df['C/A'] = titanic_df['Age'].apply(lambda x: 'child' if x<=19 else 'adult')
titanic_df[10:15]

PassengerId  Survived  Pclass                                  Name  \
10           11         1       3       Sandstrom, Miss. Marguerite Rut   
11           12         1       1              Bonnell, Miss. Elizabeth   
12           13         0       3        Saundercock, Mr. William Henry   
13           14         0       3           Andersson, Mr. Anders Johan   
14           15         0       3  Vestrom, Miss. Hulda Amanda Adolfina   

       Sex   Age  SibSp  Parch     Ticket     Fare Cabin Embarked  Name_len  \
10  female   4.0      1      1    PP 9549  16.7000    G6        S       891   
11  female  58.0      0      0     113783  26.5500  C103        S       891   
12    male  20.0      0      0  A/5. 2151   8.0500  C000        S       891   
13    male  39.0      1      5     347082  31.2750  C000        S       891   
14  female  14.0      0      0     350406   7.8542  C000        S       891   

      C/A  
10  child  
11  adult  
12  adult  
13  adult  
14  child

In [280]:
#else if는 지원하지 않지만 if, else를 두 번 사용하면 가능
titanic_df['C/A/E'] = titanic_df['Age'].apply(lambda x: 'child' if x<=19 else ('adult' if x <= 61 else 'elderly'))
titanic_df.iloc[33:40]

PassengerId  Survived  Pclass                                Name     Sex  \
33           34         0       2               Wheadon, Mr. Edward H    male   
34           35         0       1             Meyer, Mr. Edgar Joseph    male   
35           36         0       1      Holverson, Mr. Alexander Oskar    male   
36           37         1       3                    Mamee, Mr. Hanna    male   
37           38         0       3            Cann, Mr. Ernest Charles    male   
38           39         0       3  Vander Planke, Miss. Augusta Maria  female   
39           40         1       3         Nicola-Yarred, Miss. Jamila  female   

          Age  SibSp  Parch      Ticket     Fare Cabin Embarked  Name_len  \
33  66.000000      0      0  C.A. 24579  10.5000  C000        S       891   
34  28.000000      1      0    PC 17604  82.1708  C000        C       891   
35  42.000000      1      0      113789  52.0000  C000        S       891   
36  29.699118      0      0        2677   7.2292  C000        C       891   
37  21.000000      0      0  A./5. 2152   8.0500  C000        S       891   
38  18.000000      2      0      345764  18.0000  C000        S       891   
39  14.000000      1      0        2651  11.2417  C000        C       891   

      C/A    C/A/E  
33  adult  elderly  
34  adult    adult  
35  adult    adult  
36  adult    adult  
37  adult    adult  
38  child    child  
39  child    child

In [281]:
# 더 세분화된 분류는 함수를 만들면 가능 {완벽가이드 83p}

In [6]:
####데이터프레임은 리스트형태{} 데이터에서 만들때와 아래처럼 그냥 []로 만들때 가로 세로 방향이 다름 
import pandas as  pd
dd = [[1,2,3,4],[3,4,5,6],[7,4,3,2]]
pd.DataFrame(dd, index = ['one','two','three'])

0  1  2  3
one    1  2  3  4
two    3  4  5  6
three  7  4  3  2